### PR TITLE
Methods for getting user's repo/commit language distribution by username

### PR DESCRIPTION
**Pull request by kytrol**
Added an entry in .env, GITHUB_USERNAME, to be used in the Mocha tests for these methods.

### CODE REVIEW

**Comment by andrewbrooke** [comment]
This looks good! I'm changing the base branch to develop instead of master. (Trying to follow a model more like this: http://nvie.com/posts/a-successful-git-branching-model/).

Would you mind adding examples to `examples/examples.js` for the two new methods? 

Lastly, if you could update the `README.md` Usage section with the new methods, as well as the Tests section with the additional .env entry. Thanks!

The one issue that these methods bring (not your fault) is the Github API rate limit for unauthenticated requests, but I'm not sure there's much we can do about that at this point.

**Comment by andrewbrooke** [comment]
We could modify this slightly to always require an access token (so we do authenticated requests) and then allow the user to pick visibility (for their own repos) or provide a username (for someone's public repos).

Haven't tested this, but I'm assuming it'd work.

**Review by andrewbrooke — APPROVED** [review]

**Comment by kytrol** [comment]
First pull request in the books. :smile:

**Comment by andrewbrooke** [comment]
Congrats! Good stuff my dude

**Pull request merged**
